services:
  app:
    image: neeswebservice/azure
    ports:
      - "3000:3000"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /azure/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network

networks:
  caddy_network:
    driver: overlay

volumes:
  caddy_data:
  caddy_config:
